export const ActionTypes = {
  SET_ACTIVE_FOLDER: "SET_ACTIVE_FOLDER",
  SET_ACTIVE_PASSWORD: "SET_ACTIVE_PASSWORD",
  SET_ADD_FOLDER: "SET_ADD_FOLDER",
  ADD_FOLDER: "ADD_FOLDER",
  ADD_PASS: "ADD_PASS",
  SET_ADD_PASS: "SET_ADD_PASS",
  REMOVE_FOLDER: "REMOVE_FOLDER",
  REMOVE_PASS: "REMOVE_PASS",
  CHANGE_FOLDER_VALUE: "CHANGE_FOLDER_VALUE",
  CHANGE_PASSWORD_VALUE: "CHANGE_PASSWORD_VALUE",
};
